const TRACKING_EVENT_TYPES = {
  COMPANY_CREATED: 'COMPANY_CREATED',
  COMPANY_DELETED: 'COMPANY_DELETED',
  USER_CREATED: 'USER_CREATED',
  USER_DELETED: 'USER_DELETED',
  API_KEY_CREATED: 'API_KEY_CREATED',
  API_KEY_DELETED: 'API_KEY_DELETED',
  WEBHOOK_CREATED: 'WEBHOOK_CREATED',
  WEBHOOK_DELETED: 'WEBHOOK_DELETED',
  EVENT_CREATED: 'EVENT_CREATED',
  EVENT_DELETED: 'EVENT_DELETED',
  EVENT_PARTICIPANT_CREATED: 'EVENT_PARTICIPANT_CREATED',
  EVENT_PARTICIPANT_DELETED: 'EVENT_PARTICIPANT_DELETED',
  EVENT_PARTICIPANT_UNIQUE_JOINED: 'EVENT_PARTICIPANT_UNIQUE_JOINED',
  EVENT_PARTICIPANT_JOINED: 'EVENT_PARTICIPANT_JOINED',
  EVENT_PARTICIPANT_LEFT: 'EVENT_PARTICIPANT_LEFT',
  EVENT_PARTICIPANT_KICKED: 'EVENT_PARTICIPANT_KICKED',
  EVENT_MESSAGE_CREATED: 'EVENT_MESSAGE_CREATED',
  EVENT_REVIEW_CREATED: 'EVENT_REVIEW_CREATED',
};

module.exports = {
  TRACKING_EVENT_TYPES,
};
