const PERMISSIONS = {
  READ_COMPANY: 'READ_COMPANY',
  UPDATE_COMPANY: 'UPDATE_COMPANY',
  CREATE_USERS: 'CREATE_USERS',
  READ_USERS: 'READ_USERS',
  UPDATE_USERS: 'UPDATE_USERS',
  UPDATE_USER_PERMISSIONS: 'UPDATE_USER_PERMISSIONS',
  DELETE_USERS: 'DELETE_USERS',
  CREATE_API_KEYS: 'CREATE_API_KEYS',
  READ_API_KEYS: 'READ_API_KEYS',
  UPDATE_API_KEYS: 'UPDATE_API_KEYS',
  DELETE_API_KEYS: 'DELETE_API_KEYS',
  CREATE_WEBHOOKS: 'CREATE_WEBHOOKS',
  READ_WEBHOOKS: 'READ_WEBHOOKS',
  UPDATE_WEBHOOKS: 'UPDATE_WEBHOOKS',
  DELETE_WEBHOOKS: 'DELETE_WEBHOOKS',
  CREATE_EVENTS: 'CREATE_EVENTS',
  READ_EVENTS: 'READ_EVENTS',
  UPDATE_EVENTS: 'UPDATE_EVENTS',
  DELETE_EVENTS: 'DELETE_EVENTS',
  CANCEL_EVENTS: 'CANCEL_EVENTS',
  READ_EVENT_STATISTICS: 'READ_EVENT_STATISTICS',
};

const PERMISSIONS_ARRAY = Object.values(PERMISSIONS);

const USER_PERMISSIONS = {
  READ_COMPANY: 'READ_COMPANY',
  UPDATE_COMPANY: 'UPDATE_COMPANY',
  CREATE_USERS: 'CREATE_USERS',
  READ_USERS: 'READ_USERS',
  UPDATE_USERS: 'UPDATE_USERS',
  UPDATE_USER_PERMISSIONS: 'UPDATE_USER_PERMISSIONS',
  DELETE_USERS: 'DELETE_USERS',
  CREATE_API_KEYS: 'CREATE_API_KEYS',
  READ_API_KEYS: 'READ_API_KEYS',
  UPDATE_API_KEYS: 'UPDATE_API_KEYS',
  DELETE_API_KEYS: 'DELETE_API_KEYS',
  CREATE_WEBHOOKS: 'CREATE_WEBHOOKS',
  READ_WEBHOOKS: 'READ_WEBHOOKS',
  UPDATE_WEBHOOKS: 'UPDATE_WEBHOOKS',
  DELETE_WEBHOOKS: 'DELETE_WEBHOOKS',
  CREATE_EVENTS: 'CREATE_EVENTS',
  READ_EVENTS: 'READ_EVENTS',
  UPDATE_EVENTS: 'UPDATE_EVENTS',
  DELETE_EVENTS: 'DELETE_EVENTS',
  CANCEL_EVENTS: 'CANCEL_EVENTS',
  READ_EVENT_STATISTICS: 'READ_EVENT_STATISTICS',
};

const API_KEY_PERMISSIONS = {
  CREATE_USERS: 'CREATE_USERS',
  READ_USERS: 'READ_USERS',
  UPDATE_USERS: 'UPDATE_USERS',
  DELETE_USERS: 'DELETE_USERS',
  CREATE_EVENTS: 'CREATE_EVENTS',
  READ_EVENTS: 'READ_EVENTS',
  UPDATE_EVENTS: 'UPDATE_EVENTS',
  DELETE_EVENTS: 'DELETE_EVENTS',
  CANCEL_EVENTS: 'CANCEL_EVENTS',
  READ_EVENT_STATISTICS: 'READ_EVENT_STATISTICS',
};

const MANAGER_LOGGING_IN_PERMISSIONS = PERMISSIONS_ARRAY;

function isPermissionObjectValid(object) {
  return typeof object === 'object' && Object.values(object).every((perm) => PERMISSIONS_ARRAY.includes(perm));
}

if (!isPermissionObjectValid(USER_PERMISSIONS)) {
  console.error('Using invalid permission value in USER_PERMISSIONS');
  process.exit(1);
}


if (!isPermissionObjectValid(API_KEY_PERMISSIONS)) {
  console.error('Using invalid permission value in API_KEY_PERMISSIONS');
  process.exit(1);
}

module.exports = {
  PERMISSIONS,
  PERMISSIONS_ARRAY,
  USER_PERMISSIONS,
  API_KEY_PERMISSIONS,
  MANAGER_LOGGING_IN_PERMISSIONS,
};
