const {
  PORT = '3000',
  USER_JWT_SECRET,
  MANAGER_JWT_SECRET,
  EVENT_PARTICIPANT_JWT_SECRET,
  HASH_ID_SECRET,
} = process.env;

if (!USER_JWT_SECRET || !MANAGER_JWT_SECRET || !EVENT_PARTICIPANT_JWT_SECRET || !HASH_ID_SECRET) {
  console.error('Missing HASH_ID_SECRET, USER_JWT_SECRET, MANAGER_JWT_SECRET or EVENT_PARTICIPANT_JWT_SECRET');
  process.exit(1);
}

module.exports = {
  PORT: +PORT,
  USER_JWT_SECRET,
  MANAGER_JWT_SECRET,
  EVENT_PARTICIPANT_JWT_SECRET,
  HASH_ID_SECRET,
};
