const DEFAULT_CACHE_SECONDS = 60 * 60 * 24 * 1;
const DEFAULT_FILE_LIMIT_SIZE = 5 * 1024 * 1024;
const DEFAULT_FILE_PROPERTY = 'files';
const DEFAULT_FILE_LIMIT = 10;
const DEFAULT_FILE_PATH = 'files';

module.exports = {
  DEFAULT_CACHE_SECONDS,
  DEFAULT_FILE_LIMIT,
  DEFAULT_FILE_LIMIT_SIZE,
  DEFAULT_FILE_PATH,
  DEFAULT_FILE_PROPERTY,
};
