const WEBHOOK_EVENT_TYPES = {
  USER_CREATED: 'USER_CREATED',
  USER_UPDATED: 'USER_UPDATED',
  USER_DELETED: 'USER_DELETED',
  WEBHOOK_CREATED: 'WEBHOOK_CREATED',
  WEBHOOK_UPDATED: 'WEBHOOK_UPDATED',
  WEBHOOK_DELETED: 'WEBHOOK_DELETED',
  API_KEY_CREATED: 'API_KEY_CREATED',
  API_KEY_UPDATED: 'API_KEY_UPDATED',
  API_KEY_DELETED: 'API_KEY_DELETED',
  EVENT_CREATED: 'EVENT_CREATED',
  EVENT_UPDATED: 'EVENT_UPDATED',
  EVENT_DELETED: 'EVENT_DELETED',
  EVENT_PARTICIPANT_KICKED: 'EVENT_PARTICIPANT_KICKED',
  EVENT_REVIEW_CREATED: 'EVENT_REVIEW_CREATED',
};


module.exports = {
  WEBHOOK_EVENT_TYPES,
};
