const WEBHOOK_EVENT_TYPES = {
  USER_CREATED: 'USER_CREATED',
  USER_UPDATED: 'USER_UPDATED',
  USER_DELETED: 'USER_DELETED',
  EVENT_CREATED: 'EVENT_CREATED',
  EVENT_UPDATED: 'EVENT_UPDATED',
  EVENT_DELETED: 'EVENT_DELETED',
  EVENT_PARTICIPANT_KICKED: 'EVENT_PARTICIPANT_KICKED',
};


module.exports = {
  WEBHOOK_EVENT_TYPES,
};
